# Generated by Django 4.0.5 on 2022-07-05 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationrequests',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
