# Generated by Django 4.0.5 on 2022-07-05 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailconfirmationrequests_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmationrequests',
            name='duration',
        ),
        migrations.AddField(
            model_name='emailconfirmationrequests',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 21, 15, 15, 766015)),
        ),
    ]
