# Generated by Django 4.0.5 on 2022-07-05 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_emailconfirmationrequests_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationrequests',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 6, 14, 5, 289905, tzinfo=utc)),
        ),
    ]
