version: "3.9"
services:
    db:
        container_name: ATUS_db
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=db
        volumes:
            - ./databases:/var/lib/mysql

    nginx:
        container_name: ATUS_nginx
        image: nginx:1.13
        ports:
            - "25565:25565"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./backend/static_root:/usr/src/app/static_root
        depends_on:
            - db
            - frontend
            - backend

    backend:
        container_name: ATUS_backend
        build: ./backend
        expose:
            - "8000:8000"
        restart: on-failure:10
        command: bash -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            /usr/local/bin/gunicorn django51.wsgi:application -w 2 -b :8000 --reload"
        environment:
            - MYSQL_DB=db
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_HOST=db
            - DJANGO_DEBUG=True
            - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
            - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
        volumes:
            - ./backend:/usr/src/app
            - ./backend:/code

    frontend:
        container_name: ATUS_frontend
        build: ./frontend
        expose:
            - "3000:3000"
        command: "npm run dev"
        environment:
            - AXIOS_BASEURL=http://backend:8000/api
            - AXIOS_BROWSER_BASEURL=/api
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/usr/src/app
